### ISSUE TITLE
Error during export

### ISSUE THREAD

**Issue by dimmy-timmy** [noxdafox/rabbitmq-cloudwatch-exporter#10]
Rabbitmq 3.8.0-rc.1
Erlang 22.0.7

Configuration in rabbitmq.conf :
```
cloudwatch_exporter.metrics.1 = overview
cloudwatch_exporter.metrics.2 = queue
cloudwatch_exporter.metrics.3 = node
```
ECS Task IAM used for credentials
`AWS_DEFAULT_REGION` and `AWS_REGION` environment variables defined 

Stacktrace
`** {{badfun,nil},[{'Elixir.RabbitMQCloudWatchExporter.Exporter','-handle_info/2-fun-3-',1,[{file,"lib/rabbitmq_cloudwatch_exporter/exporter.ex"},{line,55}]},{'Elixir.Enum',flat_map_list,2,[{file,"lib/enum.ex"},{line,2986}]},{'Elixir.Enum',flat_map_list,2,[{file,"lib/enum.ex"},{line,2987}]},{'Elixir.RabbitMQCloudWatchExporter.Exporter',handle_info,2,[{file,"lib/rabbitmq_cloudwatch_exporter/exporter.ex"},{line,55}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}`

**Comment by noxdafox** [comment]
Hello,

The plugin was built against RMQ v3.7.x and it's bytecode is most-likely not compatible with RMQ v3.8.x. 

I am not planning to provide builds for RMQ v3.8.x until it's not declared stable.

Nevertheless, the plugin builds and operates correctly against RMQ master branch so I'd suggest to compile your own version and try to ship it. The documentation provides build instructions. Just use Elixir <= 1.8.x as per issue #9 there seems to be problem with the latest version.

**Comment by dimmy-timmy** [comment]
Thank you for quick response. 
I`ll try and let you know

**Comment by pmalon** [comment]
@noxdafox 
I think that I am getting the same error:
`
02 Jan 2020 17:31:03.112rabbit-broker rabbit[3045]: ** {{badfun,nil},[{'Elixir.RabbitMQCloudWatchExporter.Exporter','-handle_info/2-fun-3-',2,[{file,"lib/rabbitmq_cloudwatch_exporter/exporter.ex"},{line,56}]},{'Elixir.Enum',flat_map_list,2,[{file,"lib/enum.ex"},{line,2986}]},{'Elixir.Enum',flat_map_list,2,[{file,"lib/enum.ex"},{line,2987}]},{'Elixir.RabbitMQCloudWatchExporter.Exporter',handle_info,2,[{file,"lib/rabbitmq_cloudwatch_exporter/exporter.ex"},{line,56}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
02 Jan 2020 17:31:03.113rabbit-broker rabbit[3045]: 2020-01-02 17:31:03.115 [error] <0.987.0> CRASH REPORT Process <0.987.0> with 1 neighbours crashed with reason: bad function nil in 'Elixir.RabbitMQCloudWatchExporter.Exporter':'-handle_info/2-fun-3-'/2 line 56
02 Jan 2020 17:31:03.113rabbit-broker rabbit[3045]: 2020-01-02 17:31:03.116 [error] <0.777.0> Supervisor 'Elixir.Singleton.Supervisor' had child 'Elixir.Singleton.Manager' started with 'Elixir.Singleton.Manager':start_link('Elixir.RabbitMQCloudWatchExporter.Exporter', [], rabbitmq_cloudwatch_exporter, 'singleton_0bpF3SXqPZTQc80tAf+lu7E5kqQ') at <0.986.0> exit with reason bad function nil in 'Elixir.RabbitMQCloudWatchExporter.Exporter':'-handle_info/2-fun-3-'/2 line 56 in context child_terminated
02 Jan 2020 17:31:33.488`
on Rabbit `3.7.23` with Erlang version `22.2.1`
