### ISSUE TITLE
need to avoid using access key and secret key 

### ISSUE THREAD

**Issue by KursLabIgor** [noxdafox/rabbitmq-cloudwatch-exporter#13]
For configuration permissions usually assign role with required permissions. Need to use for example ec2 metadata endpoint for getting creds.

**Comment by noxdafox** [comment]
Hello,

I am not sure what you are asking.

If the issue is the need of putting the access and secret keys, please note that it's optional.

The plugin will try to guess them automatically from the environment and the instance role.

**Comment by KursLabIgor** [comment]
@noxdafox instance role this what i mean.
