### ISSUE TITLE
Support high resolution metrics 

### ISSUE THREAD

**Issue by chathsuom** [noxdafox/rabbitmq-cloudwatch-exporter#17]
We need to get metrics in fine granularity. for .e.g. 20s intervals.

`cloudwatch_exporter.export_period = 20`

Tried with setting this but still, I can see 60s intervals in cloud watch

**Comment by noxdafox** [comment]
Hello,

CloudWatch supports 2 types of metrics: 

1. Standard: the default ones with 1 minute minimum resolution
2. High Resolution: 1 second minimum resolution

This plugin publishes the metrics as standard metrics. All metric points are actually uploaded but CloudWatch aggregates them into a 1 minute period.

I can add support for high resolution metrics in the plugin but be aware that this will incur extra costs on your CloudWatch bills.

**Comment by chathsuom** [comment]
Hello, 
Thanks for the prompte response.
We need only message count on some queues to try ECS scaling. I saw there is another issue that provides selecting only for e.g. messages. 
We will have to evaluate the cost with that.
Thanks.

**Comment by noxdafox** [comment]
The configuration can only be static. Therefore, provide the requested granularity would be too cumbersome.

What I can provide, is a flag to enable high resolution on AWS CW itself. Nevertheless, it would be global for all metrics you export. Hence the costs need to be considered.

With the new version of the plugin under work you will be able to choose which metrics to export. See the [`README`](https://github.com/noxdafox/rabbitmq-cloudwatch-exporter/tree/v1) for the new version. You could export only the message queue sizes and use the high resolution together.

**Comment by chathsuom** [comment]
Do you think at a minimum, you can enable `StorageResolution`? As you said a flag may be.

**Comment by noxdafox** [comment]
Feature added in release `v1.0.0`.
