### ISSUE TITLE
Update plugin configuration in runtime (without a restart)

### ISSUE THREAD

**Issue by leechechik** [noxdafox/rabbitmq-cloudwatch-exporter#25]
I wanted to know if there is an option to update the plugin configuration without having a restart to the node.
For example: to update this parameter - `cloudwatch_exporter.metrics.queue.export_regex`

**Comment by noxdafox** [comment]
Hello,

unfortunately RabbitMQ does not provide mechanisms to dynamically change configuration values of installed plugins. You can change some parameters via the management plugin with its REST APIs but these changes only apply to its internals and not the plugins.

**Comment by leechechik** [comment]
Thanks for your answer 👍
