### ISSUE TITLE
Support for IMDSV2 

### ISSUE THREAD

**Issue by avivek** [noxdafox/rabbitmq-cloudwatch-exporter#33]
We have been using this plugin to capture the RMQ metrics @ cloudwatch for quite some time and it has been working great. Thanks a lot.

**About the Enhancement:**
The IMDS of AWS has a new version IMDSV2. 
AWS recommends that everyone migrate to the V2 version, and has settings to turn off V1 at the machine level.
This is recommended for security reasons.

The peer_discovery_aws module has moved over:
https://github.com/rabbitmq/rabbitmq-server/pull/2952

Also when I checked on the Dependency of this project ex_aws, there is a PR that is open for this:
https://github.com/ex-aws/ex_aws/pull/739

It would be really helpful if we could support this enhancement for this library.

**Comment by noxdafox** [comment]
I am not sure IMDS related changes have to do with this plugin. This plugin simply uses `ex_aws` to interface with AWS APIs.

The way `ex_aws` authenticates with AWS is out of the scope for this plugin. Is there some necessary changes to be done once said PR get merged?

**Comment by avivek** [comment]
When the IMDSV2 is supported on the ex_aws library, we need to upgrade the dependency here.
I think nothing else is required.

**Comment by avivek** [comment]
Hi @noxdafox the IMDSV2 supported has been merged by the ex_aws library.
Please refer to the below PR:

https://github.com/ex-aws/ex_aws/pull/860

Can you please update the dependency and create a release for this.

**Comment by avivek** [comment]
Hi @noxdafox,

The IMDSV2 supported has been merged by the ex_aws library.
Please refer to the below PR:

https://github.com/ex-aws/ex_aws/pull/860

Can you please update the dependency and create a release for this.

**Comment by noxdafox** [comment]
Resolved in `v1.0.4`
