### ISSUE TITLE
Missing dependencies on enabling plugin

### ISSUE THREAD

**Issue by selvathiruarul** [noxdafox/rabbitmq-cloudwatch-exporter#37]
I'm getting 

rabbitmq_cloudwatch_exporter
Error:
{:missing_dependencies, [:jsx], [:erlcloud]}

when I try to enable the plugin, this was working before.  Let me know if something is changed 

Thanks

**Comment by noxdafox** [comment]
What RabbitMQ and Erlang version are you using? `erlcloud` is actually within the release assets, are you placing it in the correct plugins folder?

**Comment by selvathiruarul** [comment]
@noxdafox: Thanks for checking this. I use Rabbitmq - 3.7.11  & Erlang - 23.3.4.4  . Yes, I placed `erlcloud-3.3.2.ez` in the correct plugins folder and I couldn't find jsx in the assets.

**Comment by selvathiruarul** [comment]
any thoughts on why `jsx-2.9.0.ez` isn't available anymore in the release assets?

**Comment by noxdafox** [comment]
`jsx-3.1.0` has bee added back to the release assets.

Please let me know if the issue persists.
