### ISSUE TITLE
Metrics export not working in ME-south-1

### ISSUE THREAD

**Issue by avivek** [noxdafox/rabbitmq-cloudwatch-exporter#41]
We have been using RMQ along with this library in many AWS regions and it has been working great.
We found that the metrics are not exported in ME-south-1 due to an issue with the dependent library ex_aws.

I have raised a PR and the same has been merged in ex_aws.
https://github.com/ex-aws/ex_aws/pull/845

Can we please update dependencies and release to fix this issue?
Thanks.

**Comment by noxdafox** [comment]
Will do this WE.

**Comment by noxdafox** [comment]
Issue fixed in `v1.0.2`.

**Comment by avivek** [comment]
@noxdafox when trying to use the new release I get the following error:

[error] <0.293.0> CRASH REPORT Process <0.293.0> with 0 neighbours exited with reason: {{missing_dependencies,[mime],[ex_aws]},{rabbit,start,[normal,[]]}} in application_master:init/4 line 138
[info] <0.44.0> Application rabbit exited with reason: {{missing_dependencies,[mime],[ex_aws]},{rabbit,start,[normal,[]]}}

WDYT??

**Comment by noxdafox** [comment]
The plugin packaging system is quite cumbersome as it produces several packages which some are RMQ dependencies (hence they come with the broker itself) and some others are plugin ones.

In this specific case, `ex_aws` included a new dependency: `mime`. 

It's quite hard to track those as they are many. I added `mime` in the list of artifacts. Please let me know if it complains with other missing dependencies.

**Comment by avivek** [comment]
@noxdafox After the addition of mime the rabbitmq instance starts up fine.
But noticed that even after that the metrics were not published in the Bahrain region.

Raised a PR 
https://github.com/ex-aws/ex_aws/pull/846

Merging this will allow for metrics export in bahrain and I have tested the same in local too.

**Comment by avivek** [comment]
hi @noxdafox 
The PR has been merged and updating should allow publishing metrics in the Middle east region.
Can you pull the latest changes please??

**Comment by avivek** [comment]
hi @noxdafox 
Can you please check this?
When you upgrade ex_aws pls also make sure that we update jason to 1.3.0 per this commit in ex-aws:
https://github.com/ex-aws/ex_aws/commit/79f15fc29698d9eff784d793d47212a2f66e6a6f

Would highly appreciate if you do this at the earliest and this will enable us to publish metrics in Bahrain region, where we have quite a few alarms based on these metrics.

**Comment by noxdafox** [comment]
Done

**Comment by avivek** [comment]
Thx. All good now.
